### PR TITLE
Drop support for php < 8.1 update dev dependencies

### PR DESCRIPTION
**Pull request by SamMousa**
Work in progress, blocked by some other PRs.

- [x] Add the logger proxy dependency as a dependency of this library after https://github.com/yiisoft/yii2-psr-log-source/pull/8 is merged and released -- it's a suggestion, which is good.
- [x] Add typed parameters and return types using union types
- [x] Improve phpdoc types
- [x] Enforce `declare(strict_types=1)`
- [x] Enforce classes to be final unless annotated with `@extendable`
- [x] Add phpstan

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #53

### CODE REVIEW

**Comment by samdark** [comment]
@SamMousa what's the plan on this one?

**Comment by SamMousa** [comment]
Well it needs your approval, ie do we want to drop old php versions for this library?

**Comment by samdark** [comment]
I'm not sure it's a good idea for the upcoming release. See https://github.com/yiisoft/yii2/discussions/19831

**Comment by SamMousa** [comment]
I guess it's not up to me. I just think it's easier to get contributions by moving smaller packages to newer PHP versions.
People can always use older versions of this library if it works for them...

**Comment by samdark** [comment]
Yes. So this one is not for the next release but can be finished for the next one.

**Comment by mtangoo** [comment]
@SamMousa  Now that PHP 7.x is long dead can you find time to finish this work so that it can be merged?
We need a release that supports 8.1 before moving our attention to higher PHP version and leave this version in maintenance mode with Yii2.2 spirit

**Comment by SamMousa** [comment]
@mtangoo i think is almost good to go; check thoroughly please.

**Comment by mtangoo** [comment]
Great! I will go through as well as request a review before merging

**Review by mtangoo — APPROVED** [review]

**Comment by mtangoo** [comment]
@SamMousa thanks for your time and efforts

**Pull request merged**
