### PR TITLE
[wip] Feat container factory

### PR DESCRIPTION
**Pull request by SamMousa**
This aims to resolve several issues related configurability. 
The idea is that the DI container will be used for creating factories.

This is a wip and will need fixes after other PRs are merged. Also it needs to be considered whether we want / need this.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by mtangoo** [comment]
Merging this PR is the only cleaner way toward a configurable extension and will allow for solving issues like https://github.com/yiisoft/yii2-symfonymailer/issues/62

I have tested locally solving the issue with this PR merged and it is easier than alternative routes.

Any objection to merging this?

**Comment by SamMousa** [comment]
No objection from me, sorry for letting this hang! Thanks for finishing it for me 😁

**Comment by mtangoo** [comment]
Thanks Sam for great contributions to Yii. Please keep them coming!

**Comment by SamMousa** [comment]
This can only be merged after #54 is merged.

**Comment by mtangoo** [comment]
Hi @SamMousa can you now resolve the conflicts on this PR?

**Comment by mtangoo** [comment]
@SamMousa would you have time to fix the conflicts for final merge.
We have to release a new version and this seems to be the last issue before that!

**Comment by SamMousa** [comment]
Thanks for pushing this over the finish line

**Comment by mtangoo** [comment]
No problem. Thanks for PR. Keep them coming!

**Pull request closed without merging**
