### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by lav45**
Fix version

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by lav45** [comment]
Composer выкачивает master ветку считая её как 2.0.* хотя она уже стала 3.0.*

**Comment by Swanty** [comment]
yii2-symfonymailer `README.md` says `// send all mails to a file by default.` but the default is already `false`:  
https://github.com/yiisoft/yii2/blob/2.0.47/framework/mail/BaseMailer.php#L79-L84  

Comment is a little misleading and made me assume it's `true` by default and that I have to always add  
`'useFileTransport' => false,` in my code or my mails would get saved to a file.
Is it possible to improve the comment? :pray:

**Comment by lav45** [comment]
@Swanty I just replaced tabs with spaces
image

You can suggest your pull request and improve the description. 
At the moment, it is more important to fix the pocket version as soon as possible so that users do not break backward compatibility.

@samdark

**Comment by Swanty** [comment]
@lav45 

Sorry, you're right, tried to piggyback the comment improvement with your pull request :smile_cat:

**Review by samdark — APPROVED** [review]

**Pull request merged**
